links = {
    'Abdominal Extension Depth Sitting': 'abdominalextensiondepthsitting',
    'Acromial Height': 'acromialheight',
    'Acromion Radiale Length': 'acromionradialelength',
    'Ankle Circumference': 'anklecircumference',
    'Axilla Height': 'axillaheight',
    'Ball of Foot Circumference': 'balloffootcircumference',
    'Ball of Foot Length': 'balloffootlength',
    'Biacromial Shoulder Breadth': 'biacromialbreadth',
    'Biceps Circumference, Flexed': 'bicepscircumferenceflexed',
    'Bicristal Hip Breadth':'bicristalbreadth',
    'Bideltoid Shoulder Breadth': 'bideltoidbreadth',
    'Bimalleolar Ankle Breadth': 'bimalleolarbreadth',
    'Bitragion Chin Arc': 'bitragionchinarc',
    'Bitragion Submandibular Arc': 'bitragionsubmandibulararc',
    'Bizygomatic Breadth': 'bizygomaticbreadth',
    'Buttocks Circumference': 'buttockcircumference',
    'Buttocks Depth': 'buttockdepth',
    'Buttocks Height': 'buttockheight',
    'Buttocks Knee Length': 'buttockkneelength',
    'Buttocks Popliteal Length': 'buttockpopliteallength',
    'Calf Circumference': 'calfcircumference',
    'Cervicale Height': 'cervicaleheight',
    'Chest Breadth': 'chestbreadth',
    'Chest Circumference': 'chestcircumference',
    'Chest Depth': 'chestdepth',
    'Chest Height': 'chestheight',
    'Crotch Height': 'crotchheight',
    'Crotch Length Omphalion': 'crotchlengthomphalion',
    'Crotch Length Posterior Omphalion': 'crotchlengthposterioromphalion',
    'Ear Breadth': 'earbreadth',
    'Ear Length': 'earlength',
    'Ear Protrusion': 'earprotrusion',
    'Elbo Wrest Height': 'elbowrestheight',
    'Eye Height Sitting': 'eyeheightsitting',
    'Foot Breadth Horizontal': 'footbreadthhorizontal',
    'Foot Length': 'footlength',
    'Forearm Center of Grip Length': 'forearmcenterofgriplength',
    'Forearm Circumference Flexed': 'forearmcircumferenceflexed',
    'Forearm-Forearm Breadth': 'forearmforearmbreadth',
    'Forearm Hand Length': 'forearmhandlength',
    'Functional Leg Length': 'functionalleglength',
    'Hand Breadth': 'handbreadth',
    'Hand Circumference': 'handcircumference',
    'Hand Length': 'handlength',
    'Head Breadth': 'headbreadth',
    'Head Circumference': 'headcircumference',
    'Head Length': 'headlength',
    'Heel Ankle Circumference': 'heelanklecircumference',
    'Heel Breadth': 'heelbreadth',
    'Hip Breadth': 'hipbreadth',
    'Hip Breadth Sitting': 'hipbreadthsitting',
    'Iliocristale Height': 'iliocristaleheight',
    'Interpupillary Breadth': 'interpupillarybreadth',
    'Interscye 1': 'interscyei',
    'Interscye 2': 'interscyeii',
    'Knee Height Mid Patella': 'kneeheightmidpatella',
    'Knee Height Sitting': 'kneeheightsitting',
    'Lateral Femoral Epicondyle Height': 'lateralfemoralepicondyleheight',
    'Lateral Malleolus Height': 'lateralmalleolusheight',
    'Lower Thigh Circumference': 'lowerthighcircumference',
    'Menton Sellion Length': 'mentonsellionlength',
    'Neck Circumference': 'neckcircumference',
    'Neck Circumference Base': 'neckcircumferencebase',
    'Overhead Fingertip Reach Sitting': 'overheadfingertipreachsitting',
    'Palm Length': 'palmlength',
    'Popliteal Height': 'poplitealheight',
    'Radiale Stylion Length': 'radialestylionlength',
    'Shoulder Circumference': 'shouldercircumference',
    'Shoulder Elbow Length': 'shoulderelbowlength',
    'Shoulder Length': 'shoulderlength',
    'Sitting Height': 'sittingheight',
    'Sleeve Length Spine Wrist': 'sleevelengthspinewrist',
    'Sleeve Outseam': 'sleeveoutseam',
    'Wingspan': 'span',
    'Height': 'stature',
    'Suprasternale Height': 'suprasternaleheight',
    'Tenth Rib Height': 'tenthribheight',
    'Thigh Circumference': 'thighcircumference',
    'Thigh Clearance': 'thighclearance',
    'Thumbtip Reach': 'thumbtipreach',
    'Tibial Height': 'tibialheight',
    'Tragion Top of Head': 'tragiontopofhead',
    'Trochanterion Height': 'trochanterionheight',
    'Vertical Trunk Circumference': 'verticaltrunkcircumferenceusa',
    'Waist Backlength': 'waistbacklength',
    'Waist Breadth': 'waistbreadth',
    'Waist Circumference': 'waistcircumference',
    'Waist Depth': 'waistdepth',
    'Waist Front Length Sitting': 'waistfrontlengthsitting',
    'Waist Height Omphalion': 'waistheightomphalion',
    'Weight (kg)': 'weightkg',
    'Wrist Circumference': 'wristcircumference',
    'Wrist Height': 'wristheight',
    'Weight (lbs)': 'Weightlbs'
    }


for key in links:
    print(f'{key}')